seml:
  executable: ../../../reference_implementations/invariance_smoothing/seml/scripts/sample_votes.py
  conda_environment: equivariance_robustness
  project_root_dir: ../../../reference_implementations/invariance_smoothing/
  output_dir: ~/logs
  name: sample_cert_dgcnn

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 4-00:00     # max time, D-HH:MM
    partition: gpu_large

fixed:

  save_dir: /your/path/to/equivariance_certification_results/modelnet40/sample

  sample_params:
    n_datapoints: 10000000
    n_samples_cert: 10000
    n_samples_pred: 1000
    batch_size: 512

  overwrite_invariance_wrapper: True

  invariance_wrapper_params:
    wrapper_type: no_wrapper
    random_sign: False
    random_order: False

  dataset:
      name: modelnet40
      data_folder: /your/path/to/modelnet/modelnet40_normal_resampled
      val_percentage: 0.2

  train_loading:
    collection: equivariance_modelnet40_train
    exp_id: None
    restrictions:
      dataset.name: modelnet40
      training_params.add_noise: True
      model.invariance_wrapper_params.wrapper_type: no_wrapper
      model.model_type: dgcnn
    find_std: True

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
    zip_id: joint_seed

  train_loading.restrictions.seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
    zip_id: joint_seed

modelnet_smoothed:    

  grid:
    sample_params.std: 
      type: choice
      options:
        #- 0.01
        #- 0.02
        #- 0.025
        #- 0.03
        #- 0.04
        - 0.05
        #- 0.06
        #- 0.07
        #- 0.075
        #- 0.08
        #- 0.09
        - 0.1
        #- 0.125
        - 0.15
        #- 0.175
        - 0.2
        #- 0.225
        - 0.25
        #- 0.3
        #- 0.4
        #- 0.5
        #- 0.6
        #- 0.7
        #- 0.75
        #- 0.8
        #- 0.9
        #- 1.0