seml:
  executable: ../../../reference_implementations/invariance_smoothing/seml/scripts/eval_forward.py
  conda_environment: equivariance_robustness
  project_root_dir: ../../../reference_implementations/invariance_smoothing/
  output_dir: ~/logs
  name: eval_forward_modelnet_rotation_arbitrary_3d

slurm:
  experiments_per_job: 1
  sbatch_options:
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM
    partition: ['cpu']
    qos: 'phdcpu'


fixed:

  save_dir: /your/path/to/equivariance_certification_results/modelnet40

  n_datapoints: 10000000
  n_samples_per_datapoint: 1

  dataset:
      name: modelnet40
      data_folder: /your/path/to/modelnet/modelnet40_normal_resampled
      val_percentage: 0.2

  pred_sample_loading:
      collection: equivariance_modelnet40_sample
      exp_id: None
      restrictions:
        dataset.name: modelnet40
      find_std: True

  threat_model_params:
    norms_delta_params:
      linspace: True
      min: 0
      max: 0.5
      steps: 50
      values: [0.0]
    distribution_params:
        parallel: False
        axis_parallel: False
        angle: 0

  certificate_params:
    baseline: True
    preprocessing: True
    tight: False
    n_samples_clean: 10000
    n_samples_pert: 10000
    alpha: 0.001
    elemental: False
    quadrature_method: clenshaw_curtis
    quadrature_degree: 20

grid:
  grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
    zip_id: joint_seed

  pred_sample_loading.restrictions.seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
    zip_id: joint_seed

  pred_sample_loading.restrictions.train_loading.restrictions.model.model_type:
    type: choice
    options:
      - pointnet
      - dgcnn

std_0-05_with_translation:
  fixed:
    std: 0.05
    certificate_params.preprocess_translation: True

std_0-1_with_translation:
  fixed:
    std: 0.1
    certificate_params.preprocess_translation: True

std_0-2_with_translation:
  fixed:
    std: 0.2
    certificate_params.preprocess_translation: True
